name = "Fomo"
uuid = "dad136d4-5f72-44bf-ab6b-685abdc56e63"
authors = ["zswh"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
SegyIO = "157a0f19-4d44-4de5-874b-87871fa26312"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
julia = "1.9, 1.10, 1.11"
CairoMakie = "0.10, 0.11, 0.12"
CUDA = "4, 5"
Interpolations = "0.14, 0.15"
JLD2 = "0.4, 0.5"
JSON = "0.21"
LoopVectorization = "0.12"
ProgressMeter = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
