name = "Fomo"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Your Name"]
version = "0.2.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.9"
CUDA = "5"
CairoMakie = "0.10, 0.11, 0.12"
JLD2 = "0.4"
JSON = "0.21"
LoopVectorization = "0.12"
ProgressMeter = "1"
